-- Create police_station_contacts table
-- This table stores contact numbers for police stations

-- Table: police_station_contacts
CREATE TABLE IF NOT EXISTS public.police_station_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_name VARCHAR(255) NOT NULL UNIQUE,
    contact_number VARCHAR(20) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_police_station_contacts_station_name ON public.police_station_contacts(station_name);
CREATE INDEX IF NOT EXISTS idx_police_station_contacts_is_active ON public.police_station_contacts(is_active);

-- Add Row Level Security (RLS) policies
ALTER TABLE public.police_station_contacts ENABLE ROW LEVEL SECURITY;

-- Policy: Allow all users to read active police station contacts
CREATE POLICY "Allow public read access to active police station contacts"
    ON public.police_station_contacts
    FOR SELECT
    USING (is_active = true);

-- Policy: Allow service role to insert/update/delete police station contacts
CREATE POLICY "Allow service role full access to police station contacts"
    ON public.police_station_contacts
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Function to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_police_station_contacts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update updated_at
CREATE TRIGGER set_police_station_contacts_updated_at
    BEFORE UPDATE ON public.police_station_contacts
    FOR EACH ROW
    EXECUTE FUNCTION update_police_station_contacts_updated_at();

-- Sample data (remove or modify for production)
-- Uncomment the lines below to insert sample data

-- INSERT INTO public.police_station_contacts (station_name, contact_number, is_active) VALUES
-- ('Thane City Police Station', '022-25345678', true),
-- ('Kalwa Police Station', '022-25345679', true),
-- ('Mumbra Police Station', '022-25345680', true),
-- ('Diva Police Station', '022-25345681', true),
-- ('Kopri Police Station', '022-25345682', true);

-- Comments for documentation
COMMENT ON TABLE public.police_station_contacts IS 'Stores contact numbers for police stations. Falls back to SOS number if station contact is not available.';
COMMENT ON COLUMN public.police_station_contacts.station_name IS 'Name of the police station (must match the police_station field in registrations table)';
COMMENT ON COLUMN public.police_station_contacts.contact_number IS 'Contact phone number for the police station';
COMMENT ON COLUMN public.police_station_contacts.is_active IS 'Whether this contact is currently active';
